### ISSUE TITLE
[litep2p-milestone]: Improve Kademlia Performance

### ISSUE THREAD

**Issue by lexnv** [paritytech/litep2p#307]
# The Vision

Enhance the performance and reliability of the litep2p Kademlia implementation to discover nodes faster.

The objective is to close the performance gap between libp2p and litep2p in terms of peer discovery speed. Currently, litep2p is approximately 3-4 times slower at discovering peers compared to libp2p.

# The Plan

To achieve this, there are a few other areas of improvement:
- the Kademlia Engine needs a refactor to transition to event driven implementation (cc https://github.com/paritytech/litep2p/pull/306)
- keep only rechable addresses in DHT or use the transport manager to extract peer addresses
- provide more than k (20) closest peers to a query response
- provide intermediate KAD record responses, not only on query completion (should help with authority discovery) 

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/litep2p/issues/40
- [ ] https://github.com/paritytech/litep2p/issues/36
- [ ] https://github.com/paritytech/litep2p/issues/53
- [ ] https://github.com/paritytech/litep2p/issues/230
- [ ] https://github.com/paritytech/litep2p/issues/209
- [ ] https://github.com/paritytech/litep2p/issues/171
- [ ] https://github.com/paritytech/litep2p/issues/168
- [ ] https://github.com/paritytech/litep2p/issues/130
- [ ] https://github.com/paritytech/litep2p/issues/81
- [ ] https://github.com/paritytech/litep2p/issues/80
- [ ] https://github.com/paritytech/litep2p/issues/232
```

**Comment by lexnv** [comment]
We have added significant kad improvements. At this point, the milestone is put on pause:

- https://forum.polkadot.network/t/announcing-the-stabilization-of-the-litep2p-network-backend/13712
