### ISSUE TITLE
[litep2p-milestone]: Stabilize the Quic Transport Layer

### ISSUE THREAD

**Issue by lexnv** [paritytech/litep2p#311]
# The Vision

Improve the robustness and fault-tolerance of the Quic protocol.

The goal is to make Quic the default transport layer for substrate-based chains running litep2p.

# The Plan

To achieve this, we need to ensure Quic operates normally using the latest quinn crate.

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/litep2p/issues/308
- [ ] https://github.com/paritytech/litep2p/issues/216
- [ ] https://github.com/paritytech/litep2p/issues/131
- [ ] https://github.com/paritytech/litep2p/issues/309
- [ ] https://github.com/paritytech/litep2p/issues/310
```
