### ISSUE TITLE
[litep2p-milestone]: Implement WebRTC transport layer

### ISSUE THREAD

**Issue by lexnv** [paritytech/litep2p#312]
# The Vision

Enhance the robustness and fault tolerance of the WebRTC protocol.

WebRTC serves as an alternative to the WebSocket transport layer, enabling lightweight client connectivity.

The goal is to establish seamless connectivity between lightweight clients (e.g., https://github.com/smol-dot/smoldot/issues/1806) and substrate-based chains over the WebRTC transport layer.

# The Plan

We need to focus on the following key areas:
- Ensuring proper implementation of the specification and maintaining smoldot connectivity
- Analyzing and optimizing memory usage to eliminate any potential memory leaks and reduce unnecessary cloning
- Implementing backpressure handling within the WebRTC layer
- Exposing detailed transport layer metrics
- Expanding and improving our testing scenarios

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/litep2p/issues/45
- [ ] https://github.com/paritytech/litep2p/issues/107
- [ ] https://github.com/paritytech/litep2p/issues/75
- [ ] https://github.com/paritytech/litep2p/issues/43
- [ ] https://github.com/paritytech/litep2p/issues/42
- [ ] https://github.com/paritytech/litep2p/issues/41
```
